name: Deploy rivianspotter.com

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch: {}     # lets you run it manually the first time

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      # No build step needed (plain HTML/JS)

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to VPS (atomic-ish)
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/

      - name: Fix perms & reload NGINX
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.DEPLOY_PATH }}
          chown -R deploy:www-data .
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
          sudo -n systemctl reload nginx || true
          EOF
